### ISSUE TITLE
Blocking has stopped working again

### ISSUE THREAD

**Issue by LordShadowFIN** [LinogeFly/hide-unwanted-streams-on-twitch#20]
That is in https://www.twitch.tv/directory and https://www.twitch.tv/directory/all etc.

If I only remembered how long it's been, but definitely at least a week, likely longer. I almost feel like Twitch is updating the site just to battle this script, because I sure don't see a change in its functionality.

**Comment by LinogeFly** [comment]
Hi,

Try to disable Twitch Beta. There is no Twitch Beta support for this plugin at the moment.

**Comment by LordShadowFIN** [comment]
As far as I'm aware, I'm not even using the beta...  :(

**Comment by LinogeFly** [comment]
Yeah, you are right. It's actually out of beta now, it seems. The extension will keep working if you use "Legacy Site" option. Temporary you can use that option. I will fix the extension soon.

**Comment by LordShadowFIN** [comment]
I probably should have specified I'm on Firefox. Sorry about that, but now I'm wondering if it's actually a Greasemonkey -issue. Still works perfectly on Chrome in Legacy as you said.

**Comment by atshum** [comment]
Just wanted to let you know Twitch Beta has launched, and there is no option to use the legacy site anymore.  I hope you can fix this extension soon.  Thanks!

**Comment by LinogeFly** [comment]
Thanks! :) Yeah, I know. I'm working on a fix already and I will release it soon (this weekend hopefully).

**Comment by LinogeFly** [comment]
OK, Chrome version should be working now. Please wait until it's udpated automatically, or use "Update extensions now" button in Chrome.

Can't update Userscript version now, because of some issues on openuserjs.org website. I will update it as soon as it will allow me to.

**Comment by LinogeFly** [comment]
Hmm, https://openuserjs.org seems to be up now, but it doesn't allow me to upload a new version of the script... I will upload newer version when I can.

**Comment by LinogeFly** [comment]
OK, userscript version of the plug-in has been updated on https://openuserjs.org also. Enjoy ;)

**Comment by Lucumo** [comment]
Unfortunately, the newest version still isn't working for me at all anymore (Firefox 49.0.2).

**Comment by LinogeFly** [comment]
Hi,

Update your Firefox to version 57 or higher and Greasemonkey extension to version 4 or higher as well.

**Comment by Lucumo** [comment]
Hm, I can't do that since any higher version starts breaking my addons which I obviously don't want. But if the version is the problem, then I guess nothing can be done. Thanks for the information though.

**Comment by imphilxd** [comment]
I have Firefox version 57 and Greasemonkey version 4. Channels that I have blocked are still appearing in my twitch/directory/all tab. I also can't block games from the directory tab.

**Comment by LinogeFly** [comment]
Yeah, looks like it got broken recently... again. I will look into it.

**Comment by imphilxd** [comment]
Oh, I deleted my comment about it not working. I upgraded to Firefox57 and uninstalled and reinstalled the addon and it seems to work again.

**Comment by LinogeFly** [comment]
Ah, ok. Yeah, and I thought it was not working for me because I had the script disabled temporary :)
